version: "3.5"
services:
  influxdb: 
    image: influxdb:1.8
    container_name: influxdb
    ports:
      - 8086:8086
      - 8088:8088
    volumes:
     - influxdb-storage:/var/lib/influxdb
    environment:
      - INFLUXDB_HTTP_AUTH_ENABLED=false
      - INFLUXDB_DB=db0
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
      - INFLUXDB_BIND_ADDRESS=0.0.0.0:8088
    restart: always
  grafana:
    image: grafana/grafana
    container_name: grafana
    depends_on:
      - influxdb
    ports:
      - 80:3000
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana-provisioning/:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    restart: always
  vuegraf:
    image: jertel/vuegraf:1.3.4
    container_name: vuegraf
    depends_on:
      - influxdb
    volumes:
      - ./config:/opt/vuegraf/conf 
    restart: always 
  tempgraf:
    build: tempgraf
    container_name: tempgraf
    depends_on:
      - influxdb
      - vuegraf
    volumes:
      - ./config:/opt/tempgraf/conf
    restart: always
volumes:
  influxdb-storage:
  grafana-storage:
