{
 "title": "Power / Weather",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "Resolution",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Total Energy Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "alias": "Energy Usage",
     "query": "SELECT mean(\"usage\") FROM \"energy_usage\" WHERE (\"device_name\" = 'Main Box-TotalUsage') AND $timeFilter GROUP BY time($Resolution) fill(none)"
    }
   ]
  },
  {
   "title": "Weather",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "Temp",
     "groupBy": [
      { "params": [ "$Resolution" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "weather",
     "select": [
      [
       { "params": [ "main_temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Humidity",
     "groupBy": [
      { "params": [ "$Resolution" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "weather",
     "select": [
      [
       { "params": [ "main_humidity" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Clouds",
     "groupBy": [
      { "params": [ "$Resolution" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "weather",
     "select": [
      [
       { "params": [ "clouds_all" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Solar VS Grid Consumption",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "alias": "$tag_device_name",
     "groupBy": [
      { "params": [ "$Resolution" ], "type": "time" },
      { "params": [ "device_name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "energy_usage",
     "query": "SELECT mean(\"usage\") FROM \"energy_usage\" WHERE (\"device_name\" =~ /^Solar.*$/) AND $timeFilter GROUP BY time(1s), \"device_name\" fill(none)",
     "select": [
      [
       { "params": [ "usage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "* -1" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "device_name", "operator": "=~", "value": "/^Solar.*$/" }
     ]
    },
    {
     "alias": "Grid Energy Usage",
     "groupBy": [
      { "params": [ "$Resolution" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "energy_usage",
     "select": [
      [
       { "params": [ "usage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "device_name", "operator": "=", "value": "Main Box" }
     ]
    }
   ]
  },
  {
   "title": "Consumption",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "alias": "$tag_device_name",
     "groupBy": [
      { "params": [ "$Resolution" ], "type": "time" },
      { "params": [ "device_name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "energy_usage",
     "select": [
      [
       { "params": [ "usage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}